# Application
spring.application.name=code-executor

# MongoDB

# Kafka
spring.kafka.bootstrap-servers=localhost:9092

# Kafka Consumer
spring.kafka.consumer.group-id=code-executor-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer